# Generated by Django 4.1.3 on 2022-11-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_trelcondi_delete_trelcond'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRelCond',
            fields=[
                ('idrelcond', models.AutoField(primary_key=True, serialize=False)),
                ('qteobjdeb', models.IntegerField(blank=True, null=True)),
                ('qteobjfin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_rel_cond',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TRelCondi',
        ),
    ]
