# Generated by Django 4.1.3 on 2022-11-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_trelcond_delete_trelcondi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='TClient',
        ),
        migrations.DeleteModel(
            name='TCommunes',
        ),
        migrations.DeleteModel(
            name='TConditionnement',
        ),
        migrations.DeleteModel(
            name='TDept',
        ),
        migrations.DeleteModel(
            name='TDtlcode',
        ),
        migrations.DeleteModel(
            name='TEnseigne',
        ),
        migrations.DeleteModel(
            name='TEntcde',
        ),
        migrations.DeleteModel(
            name='TObjet',
        ),
        migrations.DeleteModel(
            name='TPoids',
        ),
        migrations.DeleteModel(
            name='TPoidsv',
        ),
        migrations.DeleteModel(
            name='TRelCond',
        ),
        migrations.DeleteModel(
            name='TRole',
        ),
        migrations.DeleteModel(
            name='TUtilisateur',
        ),
    ]
