# to use open terminal in this directory :
# start command : docker compose up -d
# stop command : docker compose down

version: "init"

services:
  fromagerie_com_db:
    image: mysql:latest
    container_name: fromagerie_com_db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: fromagerie_com
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
