version: 'init'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports: 
      - "3306:3306"
    volumes: 
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
