# Generated by Django 4.1.3 on 2022-12-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TClient',
            fields=[
                ('codcli', models.AutoField(primary_key=True, serialize=False)),
                ('genrecli', models.CharField(blank=True, max_length=8, null=True)),
                ('nomcli', models.CharField(max_length=40)),
                ('prenomcli', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse1cli', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse2cli', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse3cli', models.CharField(blank=True, max_length=255, null=True)),
                ('cpcli', models.CharField(blank=True, max_length=5, null=True)),
                ('villecli', models.CharField(blank=True, max_length=50, null=True)),
                ('telcli', models.CharField(blank=True, max_length=10, null=True)),
                ('emailcli', models.TextField(blank=True, null=True)),
                ('portcli', models.CharField(blank=True, max_length=10, null=True)),
                ('newsletter', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCommunes',
            fields=[
                ('id_commune', models.AutoField(primary_key=True, serialize=False)),
                ('dep', models.PositiveIntegerField(blank=True, db_column='DEP', null=True)),
                ('cp', models.CharField(blank=True, db_column='CP', max_length=5, null=True)),
                ('communes', models.CharField(blank=True, db_column='COMMUNES', max_length=50, null=True)),
            ],
            options={
                'db_table': 't_communes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TDtlcode',
            fields=[
                ('codcde', models.IntegerField(blank=True, null=True)),
                ('qte', models.IntegerField(blank=True, null=True)),
                ('colis', models.IntegerField(blank=True, db_column='Colis', null=True)),
                ('commentaire', models.CharField(blank=True, db_column='Commentaire', max_length=100, null=True)),
                ('id_dtl_commande', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_dtlcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TEntcde',
            fields=[
                ('codcde', models.AutoField(primary_key=True, serialize=False)),
                ('datcde', models.DateTimeField(blank=True, null=True)),
                ('timbrecli', models.FloatField(blank=True, null=True)),
                ('timbrecde', models.FloatField(blank=True, null=True)),
                ('nbcolis', models.PositiveIntegerField(blank=True, db_column='Nbcolis', null=True)),
                ('cheqcli', models.FloatField(blank=True, null=True)),
                ('idcondit', models.IntegerField(blank=True, null=True)),
                ('cdecomt', models.TextField(blank=True, db_column='cdeComt', null=True)),
                ('barchive', models.IntegerField(blank=True, null=True)),
                ('bstock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_entcde',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TObjet',
            fields=[
                ('codobj', models.AutoField(primary_key=True, serialize=False)),
                ('libobj', models.CharField(blank=True, max_length=50, null=True)),
                ('tailleobj', models.CharField(blank=True, db_column='Tailleobj', max_length=50, null=True)),
                ('puobj', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('poidsobj', models.DecimalField(blank=True, db_column='Poidsobj', decimal_places=4, max_digits=19, null=True)),
                ('indispobj', models.IntegerField(blank=True, null=True)),
                ('o_imp', models.IntegerField(blank=True, null=True)),
                ('o_aff', models.IntegerField(blank=True, null=True)),
                ('o_cartp', models.IntegerField(blank=True, null=True)),
                ('idcondit', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('o_ordre_aff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_objet',
                'managed': False,
            },
        ),
    ]
