# Generated by Django 4.0.1 on 2022-11-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
