# Generated by Django 4.0.1 on 2022-11-30 09:45

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUtilisateur',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('code_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom_utilisateur', models.CharField(blank=True, max_length=50, null=True)),
                ('couleur_fond_utilisateur', models.IntegerField(blank=True, null=True)),
                ('date_cde_utilisateur', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.IntegerField()),
            ],
            options={
                'db_table': 't_utilisateur',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        )
    
    ]
