# Generated by Django 4.1.3 on 2022-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
