# Generated by Django 4.1.3 on 2022-12-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_tutilisateur_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
